#!/usr/bin/env python3
"""Regenerate _data/checklist_schema.yml from items*.md (run after editing checklists)."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "_data" / "checklist_schema.yml"

LABEL_RE = re.compile(
    r'<label><input type="checkbox" data-item-id="([^"]+)"\s*/>\s*(.+?)</label>',
    re.DOTALL,
)


def parse_items(path: Path) -> list[dict[str, str]]:
    raw = path.read_text(encoding="utf-8")
    if raw.startswith("---"):
        raw = raw.split("---", 2)[2]
    items: list[dict[str, str]] = []
    for m in LABEL_RE.finditer(raw):
        iid, name = m.group(1), m.group(2)
        name = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", name)
        name = re.sub(r"\{:[^}]+\}", "", name)
        name = re.sub(r"\s+", " ", name).strip()
        items.append({"id": iid, "name": name})
    return items


def main() -> None:
    pairs = [
        ("en", ROOT / "items.md"),
        ("br", ROOT / "items.br.md"),
        ("es", ROOT / "items.es.md"),
        ("ja", ROOT / "items.ja.md"),
    ]
    out: dict[str, list[dict[str, str]]] = {}
    for lang, p in pairs:
        if not p.exists():
            continue
        out[lang] = parse_items(p)

    lines = [
        "# Generated by scripts/sync-checklist-schema.py — do not hand-edit.",
        "",
    ]
    for lang, rows in out.items():
        lines.append(f"{lang}:")
        for row in rows:
            nid = row["id"].replace("\\", "\\\\").replace('"', '\\"')
            nname = row["name"].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'  - id: "{nid}"')
            lines.append(f'    name: "{nname}"')
        lines.append("")

    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    for lang, rows in out.items():
        print(f"{lang}: {len(rows)} items")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
